### ISSUE TITLE
Keyboard control not accurate

### ISSUE THREAD

**Issue by armin-reichert** [floooh/pacman.c#1]
I only tried the WASM version, not sure if the issue also exists in the desktop version: When I press a key, e. g. DOWN, before Pac-Man reaches a tile where he can move DOWN, then this should be remembered and he should move DOWN as soon as he reaches that tile. This is an essential behavior of the game.

**Comment by floooh** [comment]
Hmm, you mean when just pressing the down-direction for a short time, Pacman would move down when next possible? I cannot reproduce this in my Pacman emulator (https://floooh.github.io/tiny8bit/pacman.html), while Pacman is *looking* down when running against a wall, no movement happens in that direction. I can't test on a real arcade machine though.

The "looking down" is indeed not implemented in the C version, however Pacman's cornering should work (e.g. when you press the down direction ahead of a crossing (and keep the key pressed down all the time), Pacman will move faster around the corner since he's taking a diagonal shortcut.

**Comment by floooh** [comment]
Ah alright, now I know what you mean. Tapping the direction key within the intersection tile. I think I can fix this by testing input only when Pacman is entering a new tile.

**Comment by armin-reichert** [comment]
No, what I mean is this: Pac-Man has a current move direction (where he is looking at) and a "wish direction" which can be a different one. For example, if he is moving through a corridor to the right and the user presses the DOWN key, he remembers that direction and moves DOWN at the next tile where this is possible. However, when another direction key is pressed before that tile has been reached, this becomes the new wish direction.

**Comment by floooh** [comment]
Can you check if the Pacman emulator here behaves correctly?

https://floooh.github.io/tiny8bit/pacman.html

Press "1" to insert a coin, then any key except the cursor keys to start a game. What I'm seeing there is that while Pacman seems to remember that he wants to move downwards, he doesn't actually do so, only looks into the "wanted direction" after hitting a wall.

Only way to explain your described behaviour would be if the joystick direction bits on the Pacman hardware would be "sticky" somehow.

**Comment by armin-reichert** [comment]
This behavior feels very strange to me when the player is controlled by cursor keys. I would definitely expect the behavior I mentioned above.

**Comment by armin-reichert** [comment]
Seems like the behavior of the original/emulated game is not what you would expect for a keyboard controlled game, maybe because it was played using a joystick or something. So this is not a bug, I am closing this issue.
